/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BadgeType } from "./components/badge/badge";
export { BadgeType } from "./components/badge/badge";
export namespace Components {
    interface GlBadge {
        /**
          * It defines text of the badge
         */
        "text": string;
        /**
          * It defines type of the badge
         */
        "variant": BadgeType;
    }
}
declare global {
    interface HTMLGlBadgeElement extends Components.GlBadge, HTMLStencilElement {
    }
    var HTMLGlBadgeElement: {
        prototype: HTMLGlBadgeElement;
        new (): HTMLGlBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "gl-badge": HTMLGlBadgeElement;
    }
}
declare namespace LocalJSX {
    interface GlBadge {
        /**
          * It defines text of the badge
         */
        "text": string;
        /**
          * It defines type of the badge
         */
        "variant"?: BadgeType;
    }
    interface IntrinsicElements {
        "gl-badge": GlBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gl-badge": LocalJSX.GlBadge & JSXBase.HTMLAttributes<HTMLGlBadgeElement>;
        }
    }
}
