/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BadgeType } from "./components/badge/badge";
export { BadgeType } from "./components/badge/badge";
export namespace Components {
    interface AdaBadge {
        /**
          * It defines text of the badge
         */
        "text": string;
        /**
          * It defines type of the badge
         */
        "variant": BadgeType;
    }
    interface AdaIcon {
        /**
          * It defines name of the icon
         */
        "name": string;
        /**
          * It defines size of the icon
         */
        "size": "xs" | "s" | "m" | "l" | "xl";
    }
}
declare global {
    interface HTMLAdaBadgeElement extends Components.AdaBadge, HTMLStencilElement {
    }
    var HTMLAdaBadgeElement: {
        prototype: HTMLAdaBadgeElement;
        new (): HTMLAdaBadgeElement;
    };
    interface HTMLAdaIconElement extends Components.AdaIcon, HTMLStencilElement {
    }
    var HTMLAdaIconElement: {
        prototype: HTMLAdaIconElement;
        new (): HTMLAdaIconElement;
    };
    interface HTMLElementTagNameMap {
        "ada-badge": HTMLAdaBadgeElement;
        "ada-icon": HTMLAdaIconElement;
    }
}
declare namespace LocalJSX {
    interface AdaBadge {
        /**
          * It defines text of the badge
         */
        "text": string;
        /**
          * It defines type of the badge
         */
        "variant"?: BadgeType;
    }
    interface AdaIcon {
        /**
          * It defines name of the icon
         */
        "name"?: string;
        /**
          * It defines size of the icon
         */
        "size"?: "xs" | "s" | "m" | "l" | "xl";
    }
    interface IntrinsicElements {
        "ada-badge": AdaBadge;
        "ada-icon": AdaIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ada-badge": LocalJSX.AdaBadge & JSXBase.HTMLAttributes<HTMLAdaBadgeElement>;
            "ada-icon": LocalJSX.AdaIcon & JSXBase.HTMLAttributes<HTMLAdaIconElement>;
        }
    }
}
